services:
  app:
    container_name: app
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    depends_on:
      postgres:
        condition: service_healthy
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    env_file: ".env"
    entrypoint: /app/docker-entrypoint.sh

  postgres: 
    container_name: postgres
    image: postgres:13-alpine
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 5
    env_file: ".env"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.8
    ports:
      - 80:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file: ".env"
    

volumes:
  db-data: {}
  pgadmin-data: {}
